### ISSUE TITLE
Add tab to run final_size() over samples using {purrr}

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/finalsize#138]
The aim of this suggestion is to provide different coding alternatives and reach users with different coding styles. Also, most of the recent learning initiatives for data cleaning start teaching `tidyverse`, including `{purrr}`. 

This could use a `{.tabset}` configuration:

```
### Iterate final_size() {.tabset}

#### with {base}

#### with {purrr}
```

Here is the suggestion to add:

```
library(tibble)
library(dplyr)
library(tidyr)
library(purrr)
library(forcats)

final_size_data <- 
  
  # create a dataframe with values from a vector 
  tibble(r0 = r0_samples) %>% 
  rownames_to_column() %>% 
  
  # map the function final_size() to all the r0 values 
  # with the same set of arguments
  # with {purrr}
  mutate(temp = map(
    .x = r0,
    .f = final_size,
    contact_matrix = contact_matrix,
    demography_vector = demography_vector,
    susceptibility = susc_uniform,
    p_susceptibility = p_susc_uniform)) %>% 
  
  # unnest all the dataframe outputs in temp
  unnest(temp) %>% 
  
  # relevel the factor variable
  mutate(demo_grp = fct_relevel(demo_grp,
                                contact_data %>% 
                                  pluck("demography") %>% 
                                  pluck("age.group")))

final_size_data
```

The `final_size_data` object is equivalent to the output generated here:

https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/uncertainty_params.Rmd#L124-L152

**Comment by pratikunterwegs** [comment]
Perhaps this could be another separate PR - there's already quite a lot in #121. I could work on this after merging #121, because I can see that conflicts will arise if this were a parallel branch to `dev/fixes` and then had to be rebased on `main`.

Alternatively, you could implement this as feature branch from your fork with a PR (as with #128) - but either way I can see conflicts incoming as this branch will diverg from `main`.
